### PR TITLE
Fix #79: $not(x) is now translated as $nor[x] instead of $not(x), because apparently...

### LINKED ISSUE #79: Exception while using $not in an elemMatch
```
curl -H "Content-Type: application/json" https://`hostname`:8443/rest/data/find/migrationJob/0.1.0-SNAPSHOT?Q=objectType:migrationJob -d '{"query":{"$and":[{"field":"configurationName","op":"=","rvalue":"terms"},{"array":"jobExecutions","elemMatch":{"$not":{"field":"completedFlag","op":"$eq","rvalue":true}}}]},"projection":[{"field":"*","include":true,"recursive":true}]}' --insecure --cert /home/rdu/dcrissma/cert.pem:secret

{"status":"ERROR","modifiedCount":0,"matchCount":0,"errors":[{"objectType":"error","context":"rest/FindCommand/migrationJob/find(migrationJob:0.1.0-SNAPSHOT)/find","errorCode":"crud","msg":"{ \"serverUsed\" : \"lightbluemongo1.dev.a1.vary.redhat.com:27017\" , \"errmsg\" : \"exception: unknown operator: completedFlag\" , \"code\" : 2 , \"ok\" : 0.0}"}
```
```
2015-03-09 15:53:04,612 [hystrix-FindCommand-6] ERROR [com.redhat.lightblue.crud.mongo.MongoCRUDController] { "serverUsed" : "lightbluemongo1.dev.a1.vary.redhat.com:27017" , "errmsg" : "exception: unknown operator: completedFlag" , "code" : 2 , "ok" : 0.0}: com.mongodb.CommandFailureException: { "serverUsed" : "lightbluemongo1.dev.a1.vary.redhat.com:27017" , "errmsg" : "exception: unknown operator: completedFlag" , "code" : 2 , "ok" : 0.0}
	at com.mongodb.CommandResult.getException(CommandResult.java:76)
	at com.mongodb.CommandResult.throwOnError(CommandResult.java:131)
	at com.mongodb.DBCollection.getCount(DBCollection.java:1199)
	at com.mongodb.DBCursor.size(DBCursor.java:689)
	at com.redhat.lightblue.crud.mongo.BasicDocFinder.find(BasicDocFinder.java:66)
	at com.redhat.lightblue.crud.mongo.MongoCRUDController.find(MongoCRUDController.java:380)
	at com.redhat.lightblue.mediator.SimpleFindImpl.find(SimpleFindImpl.java:52)
	at com.redhat.lightblue.mediator.Mediator.find(Mediator.java:343)
	at com.redhat.lightblue.rest.crud.hystrix.FindCommand.run(FindCommand.java:66)
	at com.redhat.lightblue.rest.crud.hystrix.FindCommand.run(FindCommand.java:36)
	at com.netflix.hystrix.HystrixCommand$HystrixCommandFromObservableCommand$1.call(HystrixCommand.java:355)
	at com.netflix.hystrix.HystrixCommand$HystrixCommandFromObservableCommand$1.call(HystrixCommand.java:350)
	at rx.Observable$2.call(Observable.java:173)
	at rx.Observable$2.call(Observable.java:166)
	at rx.Observable.unsafeSubscribe(Observable.java:8587)
	at com.netflix.hystrix.HystrixObservableCommand$4.call(HystrixObservableCommand.java:419)
	at com.netflix.hystrix.HystrixObservableCommand$4.call(HystrixObservableCommand.java:405)
	at rx.Observable.unsafeSubscribe(Observable.java:8587)
	at rx.internal.operators.OperatorSubscribeOn$1$1.call(OperatorSubscribeOn.java:62)
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:56)
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:47)
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction.call(HystrixContexSchedulerAction.java:69)
	at com.netflix.hystrix.strategy.concurrency.HystrixContextScheduler$ThreadPoolWorker$1.run(HystrixContextScheduler.java:165)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

<@bserdar>  @dcrissman, for one thing: $not has to be outside
<@bserdar>  @dcrissman, this looks like a bug though. That query is converted to javascript. There might be something wrong with the javascript generated. Can you put the query, and this stack trace in a bug ticket for lightblue-mongo

### PR DESCRIPTION
**Pull request by bserdar**
...  $not applies to operators, not expressions.

### CODE REVIEW

File: crud/src/main/java/com/redhat/lightblue/crud/mongo/Translator.java [hunk 1]
```diff
@@ -679,7 +679,9 @@ private DBObject translateNaryFieldRelationalExpression(FieldTreeNode context, N
     }
 
     private DBObject translateUnaryLogicalExpression(FieldTreeNode context, UnaryLogicalExpression expr) {
-        return new BasicDBObject(UNARY_LOGICAL_OPERATOR_MAP.get(expr.getOp()), translate(context, expr.getQuery()));
+        List<DBObject> l=new ArrayList<>(1);
+        l.add(translate(context,expr.getQuery()));
+        return new BasicDBObject("$nor", l);
```
Comment (dcrissman) [inline crud/src/main/java/com/redhat/lightblue/crud/mongo/Translator.java]: Hard coding "$nor" instead of using the UNARY_LOGICAL_OPERATOR_MAP might be confusing to someone attempting to debug or change the value later.

Comment (bserdar) [inline crud/src/main/java/com/redhat/lightblue/crud/mongo/Translator.java]: Fixed.
