### PR TITLE
199 193

### LINKED ISSUE #199: Access checking during save fails when array elements move
It is comparing elements in array1[i] with arrat2[i], so when an array element is inserted or removed, all elements shift, failing the test

### PR DESCRIPTION
**Pull request by bserdar**
Fix #199 and #193

### CODE REVIEW

File: mongo/src/main/java/com/redhat/lightblue/mongo/crud/BsonMerge.java [hunk 1]
```diff
@@ -0,0 +1,244 @@
...
+    }
+
+    @Override
+    protected DBObject asObject(Object value) {
+        return (DBObject)value;
+    }
+
+    @Override
+    protected boolean equals(Object value1,Object value2) {
+        return (value1==null&&value2==null) ||
```
Comment (BVulaj) [inline mongo/src/main/java/com/redhat/lightblue/mongo/crud/BsonMerge.java]: First check seems redundant.

Comment (bserdar) [inline mongo/src/main/java/com/redhat/lightblue/mongo/crud/BsonMerge.java]: why?

Comment (BVulaj) [inline mongo/src/main/java/com/redhat/lightblue/mongo/crud/BsonMerge.java]: Woops, misread it.  A-OK.
